name: Expresiones

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
        dotnetversion: [6.0.x, 7.0.x]
    runs-on: ubuntu-latest
    env:
      CONFIGURATION: ${{ matrix.configuration }}
      SOLUTION_PATH: src/wpm-api/WisdomPetMedicine.sln
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ matrix.dotnetversion }}
        include-prerelease: true
    - name: Restore dependencies
      run: dotnet restore $SOLUTION_PATH
    - name: Build
      run: dotnet build $SOLUTION_PATH --configuration $CONFIGURATION  --no-restore
    - name: Información del job actual
      run: echo ${{ job.status }}
    - name: Información de la rama
      run: echo ${{ github.ref }} 
    - name: Ejecución de pruebas unitarias
      run: dotnet test $SOLUTION_PATH
      if: ${{ github.ref == 'refs/heads/main' }}
    - name: Mostrar mensaje
      run: echo 'Pruebas unitarias exitosas'
      if: ${{ success() }}