name: Variables de ambiente
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo $GITHUB_ACTION && 
             echo $GITHUB_EVENT_NAME && 
             echo $GITHUB_REPOSITORY && 
             echo $GITHUB_RUN_RUMBER &&
             echo $GITHUB_WORKFLOW &&
             echo $GITHUB_WORKSPACE &&
             echo $RUNNER_NAME &&
             echo $RUNNER_OS &&
             echo $RUNNER_ARCH
